pipeline {
    agent any
    triggers {
        githubPush()
    }
    options {
        timestamps()
    }
    stages {
        stage('Github Clone & Checkout') {
            steps {
                git branch: 'docker',
                    url: 'https://github.com/AnByoungHyun/jenkins-cicd.git',
                    credentialsId: 'github-jenkins-cicd'
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    // Docker hub 에 로그인 하기 위해 사용
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub') {
                        // Dockerfile 로 이미지 생성
                        docker.build('abhyuni/jenkins-test', './docker')
                    }
                }
            }
        }
        stage('Docker Image Push') {
            steps {
                script {
                    // Docker hub 에 로그인 하기 위해 사용
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub') {
                        def img = docker.image('abhyuni/jenkins-test')
                        img.push('latest')
                        img.push('0.1')
                    }
                }
            }
        }
    }
    post {
        cleanup {
            emailext subject: '$DEFAULT_SUBJECT',
                     to: 'abhyuni@gmail.com',
                     body: '$DEFAULT_CONTENT'
            cleanWs() // 작업영역 삭제
        }
    }
}
